name: confetti
description: Its just confetti.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  simple_animations: ^1.3.3
  flutter_launcher_icons: ^0.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

flutter_icons:
  ios: true
  android: true
  image_path_ios: "launcher/icon.png"
  image_path_android: "launcher/icon.png"
  adaptive_icon_background: "launcher/icon.png"
  adaptive_icon_foreground: "launcher/icon.png"
